### ISSUE TITLE
Consolidation/harmonization TODOs

### ISSUE THREAD

**Issue by csoneson** [fmicompbio/footprintR#21]
To consider at some point: 

- [x] Harmonize variable names (`.`, `_`, camelCase)
- [x] Harmonize messaging levels (`verbose` usage) across functions
- [x] Harmonize use of `::`. Let's try the following conventions:
    - make sure all used external functions are imported above the function using `@importFrom`
    - prefer to `@importFrom` the specific method (e.g. `SparseArray::rowSums`) instead of the generic (e.g. `BiocGenerics::rowSums`), to make it easier to see the exact method used
    - don't use the `namespace::` prefixes in the function body 
- [x] Consider removing obsolete(?) functions (`sumOverRegions`?)
- [x] Consider removing dependency on `scuttle::aggregateAcrossCells` (only used once in `readBedMethyl`)
- [x] Consider removing dependency on `stringr::str_extract` (only used once in `getAnchorRegions`)
- [x] Consider removing dependency on `purr::map` (only used once in `plotRegion`)
- [x] Add a `NEWS` file
- [x] Add examples to all exported functions
- [x] Run `BiocCheck()` and `pkgdown::build_site()` (to check that all functions are included in `_pkgdown.yml`)
- [x] Add the sticker 🙂 
- [x] Revisit on what value to use for the modification probability of implicit non-modified bases (`0` vs `0.02`)
- [x] Review the use of `>0` vs `>=0` (depending on how implicitly given modification probabilities are represented)
- [x] in `read-level-data.Rmd` set `eval=TRUE` for chunk with (currently non-functional) `rowMeans(NaArray)`

**Comment by mbstadler** [comment]
Added the sticker in 1685845

**Comment by mbstadler** [comment]
Removed `sumOverRegions()` (superseded by `getAnchorRegions()`) in 2404a9a

**Comment by mbstadler** [comment]
added a `NEWS.md` file in a2616d7e

**Comment by mbstadler** [comment]
The use of `::` has been harmonised according to the rules above in c38f3aec

**Comment by mbstadler** [comment]
Some first steps towards harmonising the messaging (`verbose` usage) in 161d23dd:

- a new utility function `.message(...)` that is mostly a drop-in replacement for message (although it doesn't support multi-part messages like in `message("this is ", "a long ", "message in multiple parts")`. It has the following advantages:
  - it automatically looks for a logical scalar `verbose` in the calling environment and only generates a message if `verbose == TRUE`
  - it is implemented via `cli::cli_inform` (see e.g. [here](https://cli.r-lib.org/)) and thus supports pluralisation and inline-markup, for example `.message("reading from {.file fname}")` which adds a link to a file, or `.message("processed {length(unique(x))} element{?s} of a total of {length(x)}")`
- replace the use of `if (verbose) { message(...) }` by `.message(...)`, possibly augmented using inline-markup

Having the messaging done by a central `.message()` would make it easy if we decide to, for example, change the styling of messages, or remove the `verbose` arguments in all functions in favour of a central config option.
 
Many of our dependencies already depend on `cli` (e.g. `ggplot2`), so this did not add any further dependencies.
Furthermore, it could easily be used to also support inline-formatting in errors and warnings by using `cli_abort` or `cli_warn` instead of `stop` and `warning`, or any of the other features that `cli` offers (emojis, progress bars, etc.).

**Comment by mbstadler** [comment]
Removed some dependencies:
- `purrr::map` (replaced by `dplyr::group_modify`) in 5dd70bfa
- `stringr::str_extract` (replace by `sub`) in 54fae054

**Comment by mbstadler** [comment]
`read-level-data.Rmd` now evaluates all code chunks (currently it uses `mean` instead of `rowMeans` which is not yet implemented and probably will not be implemented in BioC 3.20), done in 8a8a0299.

**Comment by csoneson** [comment]
> Revisit on what value to use for the modification probability of implicit non-modified bases (0 vs 0.02)

This is now set to 0 (no need to use an artificial non-zero value anymore with the change from `SparseArray` to `NaArray`). For `readModkitExtract`, the values provided in the input file (0) are used as they are.

**Comment by csoneson** [comment]
Harmonization of variable names done in 71a61d79 and ec0482f4
